ALTER TABLE users
ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'user',
ADD COLUMN settings JSONB DEFAULT '{}'::jsonb,
ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE; 