linters:
  disable:
    - golint  # deprecated
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - revive    # replacement for golint
    - gocyclo   # check function complexity
    - misspell  # check spelling
    - bodyclose # ensure HTTP response bodies are closed
    - nilerr    # check nil error handling

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - tmp/
    - .git/
  skip-files:
    - ".*_test\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: fmt:.*,io/ioutil:^Read.*
    exclude-functions:
      - (*crypto/rand.Reader).Read
      - io.Copy
      - io.ReadFull
      - rand.Read

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
    - path: internal/auth/jwt/
      text: "Error return value of .((rand.Read)|(io.ReadFull)). is not checked"
      linters:
        - errcheck
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 