linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - revive
    - gocyclo
    - misspell
    - bodyclose
    - nilerr

linters-settings:
  errcheck:
    exclude-functions:
      - (*crypto/rand.Reader).Read
      - io.Copy
      - io.ReadFull
      - rand.Read

issues:
  exclude-dirs:
    - vendor/
    - tmp/
    - .git/
  exclude-files:
    - ".*_test\\.go$"
  exclude-rules:
    - path: internal/auth/jwt/
      text: "Error return value of .((rand.Read)|(io.ReadFull)). is not checked"
      linters:
        - errcheck

output:
  formats: colored-line-number
  sort-results: true 