version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: identity_service
      POSTGRES_PASSWORD: development_only
      POSTGRES_DB: identity_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 